import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'fr' | 'ar';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, any> = {
    en: {
        back: 'Back',
        nav: {
            features: 'Features',
            challenges: 'Challenges',
            learning: 'Learning Center',
            dashboard: 'Access Dashboard',
            login: 'Log In',
            start_now: 'Start Now',
        },
        login: {
            title: 'Log in to your trading account',
            email_label: 'Email Address',
            email_placeholder: 'name@example.com',
            password_label: 'Password',
            password_placeholder: '••••••••',
            forgot_password: 'Forgot password?',
            remember_me: 'Remember me',
            submit_btn: 'Log In',
            submitting: 'Logging in...',
            no_account: "Don't have an account yet?",
            start_challenge: 'Start a challenge',
            signup: {
                create_account: 'Create Account',
                title: 'Sign Up for TradeSense AI',
                subtitle: 'Join thousands of traders mastering the markets with AI assistance.',
                first_name: 'First Name',
                last_name: 'Last Name',
                email: 'Email Address',
                password: 'Password',
                confirm_password: 'Confirm Password',
                phone: 'Phone Number',
                country: 'Country',
                creating_account: 'Creating Account...',
                success: {
                    title: 'Account Created Successfully!',
                    message: 'Welcome to TradeSense AI. You\'re being redirected to your dashboard.'
                }
            },
        },
        hero: {
            badge: 'New: Prop Firm for Africa',
            title: 'Become an AI-Funded Trader.',
            subtitle: 'TradeSense AI is the next-generation platform designed to guide African traders. Combine real-time AI analysis, premium education, and funding up to $100,000.',
            start: 'Start Challenge',
            masterclass: 'Discover MasterClass',
        },
        market: {
            title: 'Market Overview',
            subtitle: 'Indices, crypto and stocks — at a glance',
        },
        features: {
            assistant: 'Advanced AI Assistance',
            assistant_desc: 'Buy/Sell signals, risk detection and personalized trade plans in real-time.',
            signals: 'Live Signal Hub',
            signals_desc: "Stay informed with AI-generated market summaries and global economic alerts.",
            academy: 'Premium MasterClass',
            academy_desc: 'Comprehensive lessons from beginner to expert. AI-assisted risk management workshops.',
            why_title: 'Why Traders Choose TradeSense AI',
            why_1: 'A unique platform for trading, learning, and community',
            why_2: 'AI signals and risk alerts',
            why_3: 'News + social + MasterClass in one interface',
            why_4: 'Ideal for both beginners and experienced traders',
            why_5: 'Helps you make smarter decisions, faster',
        },
        pricing: {
            title: 'Choose Your Challenge',
            subtitle: 'Prove your skills and access real funds.',
            popular: 'Most Popular',
            capital: 'Virtual Capital',
            profit_target: 'Profit Target',
            max_daily_loss: 'Max Daily Loss',
            choose: 'Choose this Plan',
            features: {
                ai_basic: 'Basic AI Access',
                ai_advanced: 'Advanced AI Access',
                support: '24/7 Support',
                leverage_10: '1:10 Leverage',
                leverage_20: '1:20 Leverage',
                leverage_50: '1:50 Leverage',
                masterclass: 'MasterClass Included',
                mentor: '1-on-1 Mentorship',
                early_access: 'Early-stage Access',
                low_fees: 'Reduced Fees',
            }
        },
        social: {
            trust: 'They Trust Us',
        },
        footer: {
            copy: '© 2024 TradeSense AI. The First AI-Assisted African Prop Firm.',
        },
        learning: {
            title: 'MasterClass Learning Center',
            subtitle: 'Education, growth and risk mastery',
            beginner: 'Beginner',
            beginner_desc: 'Trading basics, charts, BUY/SELL/HOLD signals.',
            intermediate: 'Intermediate',
            intermediate_desc: 'Perfecting analysis and portfolio management.',
            advanced: 'Advanced',
            advanced_desc: 'Advanced strategies, algorithms and AI optimization 🧠.',
            risk: 'Risk Management',
            risk_desc: 'Stop-loss, sizing and drawdown control ⚠️ 🛡️.',
            webinars: 'Live Webinars',
            webinars_desc: 'Live sessions, Q&A and real-time AI demos.',
            exclusive: 'Exclusive Content',
            exclusive_desc: 'Ebooks, VIP PDFs and secret session recordings 💎.',
        },
        dashboard: {
            title: 'Trading Dashboard',
            subtitle: 'Live chart, signals and alerts',
            markets: 'Markets',
            challenge_status: 'Challenge Status',
            no_active: 'No Active Challenge',
            no_active_desc: 'You must buy a challenge to access the TradeSense AI trading dashboard.',
            view_plans: 'View Plans',
            buy: 'BUY',
            sell: 'SELL',
            positions: 'Open Positions',
            asset: 'Asset',
            type: 'Type',
            entry: 'Entry Price',
            pnl: 'PnL',
            action: 'Action',
            close: 'Close',
            no_positions: 'No open positions',
            ia_signal: 'AI Signal',
            risk_alert: 'Risk Alert',
            strategy: 'Strategy',
            alert: 'Alert',
            news_hub: 'News Hub & AI Analysis',
            signals: 'Trading Signals',
            leaderboard: 'Traders Ranking',
            community: 'Community Zone',
            light_mode: 'Light Mode',
            dark_mode: 'Dark Mode',
            exit: 'Exit',
            new_challenge: 'New Challenge',
            blocked: 'ACCOUNT BLOCKED',
            failed_reason: 'Loss rules not respected',
            passed_reason: 'Profit target reached!',
            welcome_msg: 'Welcome to TradeSense AI — API connected and NewsHub active.',
            trade_executed: 'executed',
            ia_chat: 'AI Chat',
            challenge_status_msg: 'Challenge status',
            ia_signal_msg: 'AI Analysis: Bullish bias detected in the crypto market.',
            risk_alert_msg: 'Warning: High volatility expected at 14:30.',
            strategy_msg: 'Current Strategy: Trend following (M5/H1).',
            alert_msg: 'Price Alert: BTC > 65k reached.',
            modal_details: 'Details of',
            modal_analysis: 'Detailed analysis and advanced metrics for',
            close_btn: 'Close',
            notifications: 'Notifications',
            waiting_notifications: 'Waiting for notifications...',
        },
        signals_panel: {
            title: 'Trading Signals',
            real_time: 'Real-Time',
            price: 'Price',
            high_risk: 'High Risk',
            risk: 'Risk',
            waiting_data: 'Waiting for signals data...',
        },
        leaderboard: {
            title: 'Leaderboard',
            subtitle: 'Top performing traders',
            top_10: 'Top 10 Traders',
            rank: 'Rank',
            trader: 'Trader',
            profit_pct: 'Profit %',
            total_profit: 'Total Profit',
            waiting_data: 'Waiting for leaderboard data...',
        },
        academy: {
            exclusive_btn: 'Exclusive Content',
            back_to_levels: 'Back to Levels',
            rejoin: 'Join',
            enrolled: 'Enrolled',
            points: 'Points',
            badges: 'Badges',
            next_lesson: 'Next Lesson',
            mark_complete: 'Mark as Complete',
            exclusive_title: '⭐ MasterClass: Exclusive Content',
            all_courses: '← All Courses',
            exclusive_content: '💎 Exclusive Content',
            modules: 'Modules',
            lessons_count: 'lessons',
            premium_exclusive_content: 'Premium Exclusive Content',
            lessons: 'Lessons',
            ebook_master_scalping_title: 'Master Scalping Ebook',
            ebook_master_scalping_desc: 'The ultimate guide to dominate the order book (PDF)',
            download: 'Download',
            dubai_seminar_title: 'Dubai Private Seminar 2024',
            dubai_seminar_desc: 'Institutional strategies and fund management (4K)',
            watch: 'Watch',
            more_vip_content: 'More VIP content will be unlocked with your progress...',
            category: 'Category',
            objectives: 'Objectives',
            view: 'View',
            select_module_to_see_lessons: 'Select a module to see lessons',
            no_modules_for_this_level: 'No modules for this level',
            ai_recommendations: 'AI Recommendations',
            follow: 'Follow',
            no_recommendations: 'No recommendations for now',
            webinars: 'Webinars',
            join: 'Join',
            no_webinars: 'No webinars for now',
            ebook_pro_scalping_title: 'Pro Scalping Ebook',
            pdf_premium: 'Premium PDF',
            open: 'Open',
            dubai_conference_title: 'Dubai Conference',
            video_4k_45min: '4K Video • 45 min',
            vip_access_granted: 'VIP Access Granted: Opening Dubai 4K Conference...',
            gamification: 'Gamification',
            level: 'Level',
            total_xp: 'total XP',
            trainings: 'Trainings',
            overall_progress: 'Overall Progress',
            recent_badges: 'Recent Badges',
        },
        lesson_view: {
            back: 'Back to Academy',
            loading: 'Loading...',
            not_found: 'Lesson not found',
            mastery: 'Mastery of section',
            objectives: 'Pedagogical Objectives',
            welcome: 'Welcome to this lesson dedicated to',
            deep_dive: 'In this module, we will explore in depth the key concepts of',
            prepare: 'Get ready to master these essential skills for your trading.',
            video_not_available: 'Video not available',
            prereq: 'Prereq',
        },
        news_hub: {
            title: 'News Hub',
            subtitle: 'Breaking news and market volatility',
            market_summary: 'AI Market Summary',
            filter_all: 'All',
            filter_crypto: 'Crypto',
            filter_indices: 'Indices',
            filter_stocks: 'Stocks',
            refresh: 'Refresh now',
            refreshing: '...',
            sentiment_neutral: 'No clear bias detected.',
            sentiment_updated: 'Updated every 5 min',
            waiting_summary: 'Waiting for summary...',
            live_news: 'Live News',
            news_breaking: 'Breaking News',
            waiting_data: 'Waiting for data...',
            page: 'Page',
            prev: 'Previous',
            next: 'Next',
            economic_alerts: 'Economic Alerts',
            waiting_alerts: 'Waiting for alerts...',
            sentiment_bullish: 'Bullish',
            sentiment_bearish: 'Bearish',
            sentiment_neutral_title: 'Neutral',
        },
        community_zone: {
            title: 'Community Zone',
            social: 'Social',
            description: 'A social space dedicated to traders where you can:',
            feature_1: 'Chat with friends & meet new traders',
            feature_2: 'Share strategies & join thematic groups',
            feature_3: 'Learn from experts and follow masterclasses',
            feature_4: 'Build a solid network around your growth',
            join_group: 'Join a group',
            invite_friends: 'Invite friends',
            popular_groups: 'Popular Groups',
            view_community: 'View Community',
            members: 'members',
            view: 'View',
            general: 'General',
            coming_soon: 'Soon: real-time chat, private groups, and community events.',
            join_soon_alert: 'Join feature coming soon!',
            invite_copied_alert: 'Invitation link copied!',
            groups: {
                scalp_name: 'Crypto Scalpers',
                scalp_desc: 'Intraday crypto strategies and risk management',
                swing_name: 'Swing Titans',
                swing_desc: 'Swing trading stocks & indices',
                tech_name: 'Tech Earnings Watch',
                tech_desc: 'Monitoring tech results and post-earnings plays',
                macro_name: 'Macro & Indices',
                macro_desc: 'Macro analysis, CPI/FOMC, SPY/QQQ',
            }
        },
        balance_status: {
            equity: 'Equity',
            balance: 'Balance',
            pnl_total: 'Total PnL',
            active: 'ACTIVE',
            passed: 'PASSED',
            failed: 'FAILED',
        },
        trade_buttons: {
            execution: 'Quick Execution',
            quantity: 'Quantity (Units)',
            buy: '📈 BUY',
            sell: '📉 SELL',
            processing: 'Processing...',
        },
        trading_chart: {
            live_feed: 'Live Price Feed from TradeSense Engine',
            chart_error: 'Chart initialization failed',
            chart_error_retry: 'Try refreshing the page or check your internet connection.',
            candlesticks_mas: 'Candlesticks + MAs 20/50',
        },
        checkout: {
            title: 'Personal Information',
            subtitle: 'Please enter your details to finalize your registration',
            full_name: 'Full Name',
            email: 'Email Address',
            phone: 'Phone Number',
            country: 'Country',
            continue: 'Continue to Payment',
            back_to_info: 'Back to Information',
            order_summary: 'Order Summary',
            selected_plan: 'Selected Plan',
            account_capital: 'Account Capital',
            total_to_pay: 'Total to Pay',
            payment_method: 'Payment Method',
            securing: 'Securing transaction...',
            secure_msg: 'Payment secured by 256-bit SSL encryption. Funds are released immediately after confirmation.'
        }
    },
    fr: {
        back: 'Retour',
        nav: {
            features: 'Fonctionnalités',
            challenges: 'Challenges',
            learning: 'Learning Center',
            dashboard: 'Accéder au Dashboard',
            login: 'Se connecter',
            start_now: 'Commencer',
        },
        login: {
            title: 'Connectez-vous à votre compte de trading',
            email_label: 'Adresse Email',
            email_placeholder: 'nom@exemple.com',
            password_label: 'Mot de passe',
            password_placeholder: '••••••••',
            forgot_password: 'Mot de passe oublié ?',
            remember_me: 'Se souvenir de moi',
            submit_btn: 'Se connecter',
            submitting: 'Connexion...',
            no_account: 'Pas encore de compte ?',
            start_challenge: 'Commencer un challenge',
            signup: {
                create_account: 'Créer un Compte',
                title: 'S\'inscrire à TradeSense AI',
                subtitle: 'Rejoignez des milliers de traders qui maîtrisent les marchés avec l\'assistance de l\'IA.',
                first_name: 'Prénom',
                last_name: 'Nom',
                email: 'Adresse Email',
                password: 'Mot de passe',
                confirm_password: 'Confirmer le mot de passe',
                phone: 'Numéro de téléphone',
                country: 'Pays',
                creating_account: 'Création du compte...',
                success: {
                    title: 'Compte créé avec succès !',
                    message: 'Bienvenue chez TradeSense AI. Vous êtes redirigé vers votre tableau de bord.'
                }
            },
        },
        hero: {
            badge: "Nouveau : Prop Firm pour l'Afrique",
            title: "Devenez un Trader Financé par l'IA.",
            subtitle: "TradeSense AI est la plateforme de nouvelle génération conçue pour guider les traders africains. Combinez analyses IA en temps réel, éducation premium et financement jusqu'à $100,000.",
            start: 'Start Challenge',
            masterclass: 'Découvrir la MasterClass',
        },
        market: {
            title: 'Aperçu du Marché',
            subtitle: 'Indices, crypto et actions — en un coup d’œil',
        },
        features: {
            assistant: 'Assistance IA Avancée',
            assistant_desc: 'Signaux Achat/Vente, détection de risques et plans de trade personnalisés en temps réel.',
            signals: "Hub d'Actualités Direct",
            signals_desc: "Restez informé avec des résumés de marché créés par l'IA et des alertes économiques mondiales.",
            academy: 'MasterClass Premium',
            academy_desc: "Leçons complètes du débutant à l'expert. Ateliers de gestion des risques assistés par IA.",
            why_title: 'Pourquoi les Traders Choisissent TradeSense AI',
            why_1: "Une plateforme unique pour le trading, l'apprentissage et la communauté",
            why_2: "Signaux IA et alertes de risque",
            why_3: "Actus + social + MasterClass dans une seule interface",
            why_4: "Idéal pour les débutants et les traders expérimentés",
            why_5: "Vous aide à prendre des décisions plus intelligentes, plus rapidement",
        },
        pricing: {
            title: 'Choisissez Votre Challenge',
            subtitle: 'Prouvez vos compétences et accédez à des fonds réels.',
            popular: 'Le Plus Populaire',
            capital: 'Capital Virtuel',
            profit_target: 'Objectif de Profit',
            max_daily_loss: 'Perte Max Quotidienne',
            choose: 'Choisir ce Plan',
            features: {
                ai_basic: 'Accès IA Basique',
                ai_advanced: 'Accès IA Avancé',
                support: 'Support 24/7',
                leverage_10: 'Levier 1:10',
                leverage_20: 'Levier 1:20',
                leverage_50: 'Levier 1:50',
                masterclass: 'MasterClass Incluse',
                mentor: 'Mentorat 1-on-1',
                early_access: 'Accès Privilégié',
                low_fees: 'Frais Réduits',
            }
        },
        social: {
            trust: 'Ils nous font confiance',
        },
        footer: {
            copy: '© 2024 TradeSense AI. La Première Prop Firm Africaine Assistée par IA.',
        },
        learning: {
            title: "Centre d'Apprentissage MasterClass",
            subtitle: "Éducation, croissance et maîtrise du risque",
            beginner: 'Débutant',
            beginner_desc: 'Bases du trading, graphiques, signaux BUY/SELL/HOLD.',
            intermediate: 'Intermédiaire',
            intermediate_desc: 'Perfectionnement des analyses et gestion de portefeuille.',
            advanced: 'Avancé',
            advanced_desc: 'Stratégies avancées, algorithmes et optimisation IA 🧠.',
            risk: 'Gestion des Risques',
            risk_desc: 'Stop-loss, sizing et contrôle de drawdown ⚠️ 🛡️.',
            webinars: 'Webinaires en Direct',
            webinars_desc: 'Sessions live, Q&A et démos IA en temps réel.',
            exclusive: 'Contenu Exclusif',
            exclusive_desc: 'Ebooks, PDFs VIP et enregistrements de sessions secrètes 💎.',
        },
        dashboard: {
            title: 'Dashboard Trading',
            subtitle: 'Graphique live, signaux et alertes',
            markets: 'Marchés',
            challenge_status: 'Statut Challenge',
            no_active: 'Aucun Challenge Actif',
            no_active_desc: 'Vous devez acheter un challenge pour accéder au dashboard de trading TradeSense AI.',
            view_plans: 'Voir les Plans',
            buy: 'ACHETER',
            sell: 'VENDRE',
            positions: 'Positions Ouvertes',
            asset: 'Actif',
            type: 'Type',
            entry: 'Prix Entrée',
            pnl: 'PnL',
            action: 'Action',
            close: 'Fermer',
            no_positions: 'Aucune position ouverte',
            ia_signal: 'IA Signal',
            risk_alert: 'Risk Alert',
            strategy: 'Stratégie',
            alert: 'Alerte',
            news_hub: 'News Hub & Analyse IA',
            signals: 'Signaux de Trading',
            leaderboard: 'Classement Traders',
            community: 'Zone Communautaire',
            light_mode: 'Mode Clair',
            dark_mode: 'Mode Sombre',
            exit: 'Sortie',
            new_challenge: 'Nouveau Challenge',
            blocked: 'COMPTE BLOQUÉ',
            failed_reason: 'Règles de perte non respectées',
            passed_reason: 'Objectif de profit atteint !',
            welcome_msg: 'Bienvenue sur TradeSense AI — API connectée et NewsHub actif.',
            trade_executed: 'exécuté',
            ia_chat: 'Chat IA',
            challenge_status_msg: 'Statut du challenge',
            ia_signal_msg: 'Analyse IA: Biais haussier détecté sur le marché crypto.',
            risk_alert_msg: 'Attention : Volatilité élevée attendue à 14h30.',
            strategy_msg: 'Stratégie actuelle : Tendance suivie (M5/H1).',
            alert_msg: 'Alerte de prix : BTC > 65k atteint.',
            modal_details: 'Détails de',
            modal_analysis: 'Analyse détaillée et métriques avancées pour',
            close_btn: 'Fermer',
            notifications: 'Notifications',
            waiting_notifications: 'En attente de notifications…',
        },
        academy: {
            exclusive_btn: 'Contenu Exclusif',
            back_to_levels: 'Retour aux Niveaux',
            rejoin: 'Rejoindre',
            enrolled: 'Inscrit',
            points: 'Points',
            badges: 'Badges',
            next_lesson: 'Leçon Suivante',
            mark_complete: 'Marquer comme terminé',
            exclusive_title: '⭐ MasterClass : Contenu Exclusif',
            all_courses: '← Tous les cours',
            exclusive_content: '💎 Contenu exclusif',
            modules: 'Modules',
            lessons_count: 'leçons',
            premium_exclusive_content: 'Contenu Exclusif Premium',
            lessons: 'Leçons',
            ebook_master_scalping_title: 'Ebook Master Scalping',
            ebook_master_scalping_desc: "Le guide ultime pour dominer le carnet d'ordres (PDF)",
            download: 'Télécharger',
            dubai_seminar_title: 'Séminaire Privé Dubaï 2024',
            dubai_seminar_desc: 'Stratégies institutionnelles et gestion de fonds (4K)',
            watch: 'Regarder',
            more_vip_content: 'Plus de contenu VIP sera débloqué avec votre progression...',
            category: 'Catégorie',
            objectives: 'Objectifs',
            view: 'Voir',
            select_module_to_see_lessons: 'Sélectionnez un module pour voir les leçons',
            no_modules_for_this_level: 'Aucun module pour ce niveau',
            ai_recommendations: 'Recommandations IA',
            follow: 'Suivre',
            no_recommendations: 'Aucune recommandation pour le moment',
            webinars: 'Webinaires',
            join: 'Rejoindre',
            no_webinars: 'Aucun webinaire pour le moment',
            ebook_pro_scalping_title: 'Ebook Pro Scalping',
            pdf_premium: 'PDF Premium',
            open: 'Ouvrir',
            dubai_conference_title: 'Conférence Dubaï',
            video_4k_45min: 'Vidéo 4K • 45 min',
            vip_access_granted: 'Accès VIP accordé : Ouverture de la Conférence Dubaï 4K...',
            gamification: 'Gamification',
            level: 'Niveau',
            total_xp: 'XP total',
            trainings: 'Formations',
            overall_progress: 'Progression globale',
            recent_badges: 'Badges récents',
        },
        lesson_view: {
            back: "Retour à l'Académie",
            loading: 'Chargement...',
            not_found: 'Leçon introuvable',
            mastery: 'Maîtrise de la section',
            objectives: 'Objectifs pédagogiques',
            welcome: 'Bienvenue dans cette leçon dédiée à',
            deep_dive: 'Dans ce module, nous allons explorer en profondeur les concepts clés de',
            prepare: 'Préparez-vous à maîtriser ces compétences essentielles pour votre trading.',
            video_not_available: 'Vidéo non disponible',
            prereq: 'Prérequis',
        },
        news_hub: {
            title: 'News Hub',
            subtitle: 'Breaking news et volatilité du marché',
            market_summary: 'Résumé IA du Marché',
            filter_all: 'Tous',
            filter_crypto: 'Crypto',
            filter_indices: 'Indices',
            filter_stocks: 'Actions',
            refresh: 'Rafraîchir maintenant',
            refreshing: '…',
            sentiment_neutral: 'Aucun biais clair détecté.',
            sentiment_updated: 'Actualisé toutes les 5 min',
            waiting_summary: 'En attente du résumé…',
            live_news: 'Actualités en Direct',
            news_breaking: 'Breaking News',
            waiting_data: 'En attente de données…',
            page: 'Page',
            prev: 'Précédent',
            next: 'Suivant',
            economic_alerts: 'Alertes Économiques',
            waiting_alerts: 'En attente d’alertes…',
            sentiment_bullish: 'Bullish',
            sentiment_bearish: 'Bearish',
            sentiment_neutral_title: 'Neutral',
        },
        signals_panel: {
            title: 'Signaux de Trading IA',
            real_time: 'Temps Réel',
            waiting_data: 'En attente de données…',
            price: 'Prix',
            high_risk: 'Risque Élevé',
            risk: 'Risque',
        },
        leaderboard: {
            title: 'Leaderboard',
            subtitle: 'Classement et performance',
            top_10: 'Classement - Top 10',
            rank: '#',
            trader: 'Trader',
            profit_pct: 'Profit %',
            total_profit: 'Profit total',
            waiting_data: 'En attente de données…',
        },
        community_zone: {
            title: 'Zone Communautaire',
            social: 'Social',
            description: 'Un espace social dédié aux traders où vous pouvez :',
            feature_1: 'Discuter avec des amis & rencontrer de nouveaux traders',
            feature_2: 'Partager des stratégies & rejoindre des groupes thématiques',
            feature_3: 'Apprendre des experts et suivre des masterclass',
            feature_4: 'Construire un réseau solide autour de votre croissance',
            join_group: 'Rejoindre un groupe',
            invite_friends: 'Inviter des amis',
            popular_groups: 'Groupes populaires',
            view_community: 'Voir la Communauté',
            members: 'membres',
            view: 'Voir',
            general: 'Général',
            coming_soon: 'Bientôt : chat en temps réel, groupes privés, et événements communautaires.',
            join_soon_alert: 'Fonctionnalité Rejoindre bientôt disponible !',
            invite_copied_alert: 'Lien d\'invitation copié !',
            groups: {
                scalp_name: 'Crypto Scalpers',
                scalp_desc: 'Stratégies intraday crypto et risk management',
                swing_name: 'Swing Titans',
                swing_desc: 'Swing trading actions & indices',
                tech_name: 'Tech Earnings Watch',
                tech_desc: 'Surveillance des résultats tech et plays post-earnings',
                macro_name: 'Macro & Indices',
                macro_desc: 'Analyse macro, CPI/FOMC, SPY/QQQ',
            }
        },
        balance_status: {
            equity: 'Equity',
            balance: 'Solde',
            pnl_total: 'PnL Total',
            active: 'ACTIF',
            passed: 'RÉUSSI',
            failed: 'ÉCHOUÉ',
        },
        trade_buttons: {
            execution: 'Exécution Rapide',
            quantity: 'Quantité (Units)',
            buy: '📈 Acheter',
            sell: '📉 Vendre',
            processing: 'En cours...',
        },
        trading_chart: {
            live_feed: 'Flux de prix en direct du moteur TradeSense',
            chart_error: "Échec de l'initialisation du graphique",
            chart_error_retry: "Essayez d’actualiser la page ou vérifiez la connexion internet.",
            candlesticks_mas: 'Candlesticks + MAs 20/50',
        },
        checkout: {
            title: 'Informations Personnelles',
            subtitle: 'Veuillez entrer vos coordonnées pour finaliser votre inscription',
            full_name: 'Nom Complet',
            email: 'Adresse Email',
            phone: 'Numéro de Téléphone',
            country: 'Pays',
            continue: 'Continuer vers le Paiement',
            back_to_info: 'Retour aux Informations',
            order_summary: 'Résumé de la Commande',
            selected_plan: 'Plan Sélectionné',
            account_capital: 'Capital du Compte',
            total_to_pay: 'Total à Payer',
            payment_method: 'Moyen de Paiement',
            securing: 'Sécurisation de la transaction...',
            secure_msg: 'Paiement sécurisé par cryptage SSL 256-bits. Les fonds sont débloqués immédiatement après confirmation.'
        }
    },
    ar: {
        back: 'رجوع',
        nav: {
            features: 'الميزات',
            challenges: 'التحديات',
            learning: 'مركز التعلم',
            dashboard: 'لوحة التحكم',
            login: 'تسجيل الدخول',
            start_now: 'ابدأ الآن',
        },
        login: {
            title: 'تسجيل الدخول إلى حساب التداول الخاص بك',
            email_label: 'البريد الإلكتروني',
            email_placeholder: 'name@example.com',
            password_label: 'كلمة المرور',
            password_placeholder: '••••••••',
            forgot_password: 'هل نسيت كلمة المرور؟',
            remember_me: 'تذكرني',
            submit_btn: 'تسجيل الدخول',
            submitting: 'جاري تسجيل الدخول...',
            no_account: 'ليس لديك حساب بعد؟',
            start_challenge: 'ابدأ التحدي',
            signup: {
                create_account: 'إنشاء حساب',
                title: 'التسجيل في TradeSense AI',
                subtitle: 'انضم إلى آلاف المتداولين الذين يتقنون الأسواق بمساعدة الذكاء الاصطناعي.',
                first_name: 'الاسم الأول',
                last_name: 'اسم العائلة',
                email: 'البريد الإلكتروني',
                password: 'كلمة المرور',
                confirm_password: 'تأكيد كلمة المرور',
                phone: 'رقم الهاتف',
                country: 'البلد',
                creating_account: 'جاري إنشاء الحساب...',
                success: {
                    title: 'تم إنشاء الحساب بنجاح!',
                    message: 'مرحباً بكم في TradeSense AI. جاري إعادة توجيهك إلى لوحة التحكم الخاصة بك.'
                }
            },
        },
        hero: {
            badge: 'جديد: شركة تداول ممولة لإفريقيا',
            title: 'كن متداولاً ممولاً بالذكاء الاصطناعي.',
            subtitle: 'TradeSense AI هي منصة الجيل القادم المصممة لتوجيه المتداولين الأفارقة. اجمع بين تحليلات الذكاء الاصطناعي في الوقت الفعلي ، والتعليم المتميز ، وتمويل يصل إلى 100,000 دولار.',
            start: 'ابدأ التحدي',
            masterclass: 'اكتشف الماستر كلاس',
        },
        market: {
            title: 'نظرة عامة على السوق',
            subtitle: 'المؤشرات والعملات الرقمية والأسهم - لمحبة خاطفة',
        },
        features: {
            assistant: 'مساعدة ذكاء اصطناعي متقدمة',
            assistant_desc: 'إشارات البيع والشراء، وكشف المخاطر، وخطط تداول مخصصة في الوقت الفعلي.',
            signals: 'مركز الإشارات المباشرة',
            signals_desc: "ابق على اطلاع بملخصات السوق الناتجة عن الذكاء الاصطناعي والتنبيهات الاقتصادية العالمية.",
            academy: 'ماستر كلاس متميز',
            academy_desc: 'دروس شاملة من المبتدئ إلى الخبير. ورش عمل إدارة المخاطر بمساعدة الذكاء الاصطناعي.',
            why_title: 'لماذا يختار المتداولون TradeSense AI',
            why_1: 'منصة فريدة للتداول والتعلم والمجتمع',
            why_2: 'إشارات الذكاء الاصطناعي وتنبيهات المخاطر',
            why_3: 'أخبار + اجتماعي + ماستر كلاس في واجهة واحدة',
            why_4: 'مثالي للمبتدئين والمتداولين ذوي الخبرة',
            why_5: 'يساعدك على اتخاذ قرارات أذكى وأسرع',
        },
        pricing: {
            title: 'اختر تحديك',
            subtitle: 'أثبت مهاراتك واحصل على أموال حقيقية.',
            popular: 'الأكثر شعبية',
            capital: 'رأس المال الافتراضي',
            profit_target: 'هدف الربح',
            max_daily_loss: 'أقصى خسارة يومية',
            choose: 'اختر هذه الخطة',
            features: {
                ai_basic: 'وصول أساسي للذكاء الاصطناعي',
                ai_advanced: 'وصول متقدم للذكاء الاصطناعي',
                support: 'دعم 24/7',
                leverage_10: 'رافعة مالية 1:10',
                leverage_20: 'رافعة مالية 1:20',
                leverage_50: 'رافعة مالية 1:50',
                masterclass: 'ماستر كلاس متضمن',
                mentor: 'توجيه 1-on-1',
                early_access: 'وصول مبكر',
                low_fees: 'رسوم منخفضة',
            }
        },
        social: {
            trust: 'نحن محل ثقة',
        },
        footer: {
            copy: '© 2024 TradeSense AI. أول شركة تداول ممولة أفريقية مدعومة بالذكاء الاصطناعي.',
        },
        learning: {
            title: 'مركز تعلم الماستر كلاس',
            subtitle: 'التعليم والنمو وإتقان المخاطر',
            beginner: 'مبتدئ',
            beginner_desc: 'أساسيات التداول، الرسوم البيانية، إشارات الشراء/البيع/الانتظار.',
            intermediate: 'متوسط',
            intermediate_desc: 'إإتقان التحليل وإدارة المحفظة.',
            advanced: 'متقدم',
            advanced_desc: 'استراتيجيات متقدمة، خوارزميات وتحسين الذكاء الاصطناعي 🧠.',
            risk: 'إدارة المخاطر',
            risk_desc: 'وقف الخسارة، التحجيم والتحكم في التراجع ⚠️ 🛡️.',
            webinars: 'ندوات مباشرة',
            webinars_desc: 'جلسات مباشرة، أسئلة وأجوبة وعروض توضيحية للذكاء الاصطناعي في الوقت الفعلي.',
            exclusive: 'محتوى حصري',
            exclusive_desc: 'كتب إلكترونية، ملفات PDF لكبار الشخصيات وتسجيلات الجلسات السرية 💎.',
        },
        dashboard: {
            title: 'لوحة تحكم التداول',
            subtitle: 'رسم بياني مباشر وإشارات وتنبيهات',
            markets: 'الأسواق',
            challenge_status: 'حالة التحدي',
            no_active: 'لا يوجد تحدي نشط',
            no_active_desc: 'يجب عليك شراء تحدٍ للوصول إلى لوحة تداول TradeSense AI.',
            view_plans: 'عارض الخطط',
            buy: 'شراء',
            sell: 'بيع',
            positions: 'المراكز المفتوحة',
            asset: 'الأصل',
            type: 'النوع',
            entry: 'سعر الدخول',
            pnl: 'الربح والخسارة',
            action: 'إجراء',
            close: 'إغلاق',
            no_positions: 'لا يوجد مراكز مفتوحة',
            ia_signal: 'إشارة الذكاء الاصطناعي',
            risk_alert: 'تنبيه المخاطر',
            strategy: 'استراتيجية',
            alert: 'تنبيه',
            news_hub: 'مركز الأخبار وتحليل الذكاء الاصطناعي',
            signals: 'إشارات التداول',
            leaderboard: 'ترتيب المتداولين',
            community: 'منطقة المجتمع',
            light_mode: 'الوضع الفاتح',
            dark_mode: 'الوضع الداكن',
            exit: 'خروج',
            new_challenge: 'تحدي جديد',
            blocked: 'الحساب مغلق',
            failed_reason: 'لم يتم احترام قواعد الخسارة',
            passed_reason: 'تم الوصول إلى هدف الربح!',
            welcome_msg: 'مرحباً بكم في TradeSense AI - تم الاتصال بـ API و NewsHub نشط.',
            trade_executed: 'تم التنفيذ',
            ia_chat: 'دردشة الذكاء الاصطناعي',
            challenge_status_msg: 'حالة التحدي',
            ia_signal_msg: 'تحليل الذكاء الاصطناعي: تم اكتشاف انحياز صعودي في سوق الكريبتو.',
            risk_alert_msg: 'تحذير: تقلبات عالية متوقعة في 14:30.',
            strategy_msg: 'الاستراتيجية الالية: متابعة الاتجاه (M5/H1).',
            alert_msg: 'تنبيه السعر: تم الوصول إلى BTC > 65k.',
            modal_details: 'تفاصيل',
            modal_analysis: 'تحليل مفصل ومقاييس متقدمة لـ',
            close_btn: 'إغلاق',
            notifications: 'التنبيهات',
            waiting_notifications: 'في انتظار التنبيهات...',
        },
        academy: {
            exclusive_btn: 'محتوى حصري',
            back_to_levels: 'العودة إلى المستويات',
            rejoin: 'انضمام',
            enrolled: 'مشترك',
            points: 'نقاط',
            badges: 'شارات',
            next_lesson: 'الدرس التالي',
            mark_complete: 'تحديد كمكتمل',
            exclusive_title: '⭐ ماستر كلاس: محتوى حصري',
            all_courses: '← جميع الدورات',
            exclusive_content: '💎 محتوى حصري',
            modules: 'الوحدات',
            lessons_count: 'دروس',
            premium_exclusive_content: 'محتوى حصري متميز',
            lessons: 'دروس',
            ebook_master_scalping_title: 'كتاب تعلم السكالبينج',
            ebook_master_scalping_desc: 'الدليل النهائي للسيطرة على سجل الأوامر (PDF)',
            download: 'تحميل',
            dubai_seminar_title: 'ندوة دبي الخاصة 2024',
            dubai_seminar_desc: 'استراتيجيات مؤسسية وإدارة الصناديق (4K)',
            watch: 'مشاهدة',
            more_vip_content: 'سيتم فتح المزيد من محتوى VIP مع تقدمك...',
            category: 'فئة',
            objectives: 'أهداف',
            view: 'عرض',
            select_module_to_see_lessons: 'اختر وحدة لعرض الدروس',
            no_modules_for_this_level: 'لا يوجد وحدات لهذا المستوى',
            ai_recommendations: 'توصيات الذكاء الاصطناعي',
            follow: 'متابعة',
            no_recommendations: 'لا توجد توصيات حالياً',
            webinars: 'ندوات',
            join: 'انضمام',
            no_webinars: 'لا توجد ندوات حالياً',
            ebook_pro_scalping_title: 'كتاب السكالبينج الاحترافي',
            pdf_premium: 'PDF متميز',
            open: 'فتح',
            dubai_conference_title: 'مؤتمر دبي',
            video_4k_45min: 'فيديو 4K • 45 دقيقة',
            vip_access_granted: 'تم منح وصول VIP: فتح مؤتمر دبي 4K...',
            gamification: 'اللعب',
            level: 'مستوى',
            total_xp: 'إجمالي XP',
            trainings: 'تدريبات',
            overall_progress: 'التقدم العام',
            recent_badges: 'شارات حديثة',
        },
        lesson_view: {
            back: 'العودة إلى الأكاديمية',
            loading: 'جاري التحميل...',
            not_found: 'الدرس غير موجود',
            mastery: 'إتقان قسم',
            objectives: 'الأهداف التعليمية',
            welcome: 'مرحباً بكم في هذا الدرس المخصص لـ',
            deep_dive: 'في هذه الوحدة سنستكشف بعمق المفاهيم الأساسية لـ',
            prepare: 'استعد لإتقان هذه المهارات الأساسية لتداولك.',
            video_not_available: 'الفيديو غير متوفر',
            prereq: 'المتطلبات',
        },
        news_hub: {
            title: 'مركز الأخبار',
            subtitle: 'الأخبار العاجلة وتقلبات السوق',
            market_summary: 'ملخص السوق بالذكاء الاصطناعي',
            filter_all: 'الكل',
            filter_crypto: 'كريبتو',
            filter_indices: 'مؤشرات',
            filter_stocks: 'أسهم',
            refresh: 'تحديث الآن',
            refreshing: '…',
            sentiment_neutral: 'لم يتم اكتشاف انحياز واضح.',
            sentiment_updated: 'يتم التحديث كل 5 دقائق',
            waiting_summary: 'في انتظار الملخص...',
            live_news: 'الأخبار المباشرة',
            news_breaking: 'أخبار عاجلة',
            waiting_data: 'في انتظار البيانات...',
            page: 'صفحة',
            prev: 'السابق',
            next: 'التالي',
            economic_alerts: 'تنبيهات اقتصادية',
            waiting_alerts: 'في انتظار التنبيهات...',
            sentiment_bullish: 'صعودي',
            sentiment_bearish: 'هبوطي',
            sentiment_neutral_title: 'محايد',
        },
        signals_panel: {
            title: 'إشارات التداول بالذكاء الاصطناعي',
            real_time: 'في الوقت الحقيقي',
            waiting_data: 'في انتظار البيانات...',
            price: 'السعر',
            high_risk: 'مخاطر عالية',
            risk: 'مخاطر',
        },
        leaderboard: {
            title: 'لوحة المتصدرين',
            subtitle: 'الترتيب والأداء',
            top_10: 'الترتيب - أفضل 10',
            rank: '#',
            trader: 'متداول',
            profit_pct: 'الربح %',
            total_profit: 'إجمالي الربح',
            waiting_data: 'في انتظار البيانات...',
        },
        community_zone: {
            title: 'منطقة المجتمع',
            social: 'اجتماعي',
            description: 'مساحة اجتماعية مخصصة للمتداولين حيث يمكنك:',
            feature_1: 'الدردشة مع الأصدقاء ومقابلة متداولين جدد',
            feature_2: 'مشاركة الاستراتيجيات والانضمام إلى مجموعات موضوعية',
            feature_3: 'التعلم من الخبراء ومتابعة الماستر كلاس',
            feature_4: 'بناء شبكة قوية حول نموك',
            join_group: 'انضمام إلى مجموعة',
            invite_friends: 'دعوة الأصدقاء',
            popular_groups: 'مجموعات شائعة',
            view_community: 'عرض المجتمع',
            members: 'أعضاء',
            view: 'عرض',
            general: 'عام',
            coming_soon: 'قريباً: دردشة في الوقت الفعلي، مجموعات خاصة، وفعاليات مجتمعية.',
            join_soon_alert: 'ميزة الانضمام ستتوفر قريباً!',
            invite_copied_alert: 'تم نسخ رابط الدعوة!',
            groups: {
                scalp_name: 'مضاربو الكريبتو',
                scalp_desc: 'استراتيجيات الكريبتو اليومية وإدارة المخاطر',
                swing_name: 'عمالقة السوينغ',
                swing_desc: 'تداول السوينغ للأسهم والمؤشرات',
                tech_name: 'مراقبة أرباح التكنولوجيا',
                tech_desc: 'مراقبة نتائج التكنولوجيا وتداولات ما بعد الأرباح',
                macro_name: 'الماكرو والمؤشرات',
                macro_desc: 'التحليل الكلي، CPI/FOMC، SPY/QQQ',
            }
        },
        balance_status: {
            equity: 'العدالة',
            balance: 'الرصيد',
            pnl_total: 'إجمالي الربح والخسارة',
            active: 'نشط',
            passed: 'ناجح',
            failed: 'فاشل',
        },
        trade_buttons: {
            execution: 'تنفيذ سريع',
            quantity: 'الكمية (وحدات)',
            buy: '📈 شراء',
            sell: '📉 بيع',
            processing: 'جاري التنفيذ...',
        },
        trading_chart: {
            live_feed: 'تغذية سعر مباشرة من محرك TradeSense',
            chart_error: 'فشل تهيئة الرسم البياني',
            chart_error_retry: 'حاول تحديث الصفحة أو تحقق من اتصال الإنترنت.',
            candlesticks_mas: 'الشموع اليابانية + المتوسطات المتحركة 20/50',
        },
        checkout: {
            title: 'المعلومات الشخصية',
            subtitle: 'يرجى إدخال بياناتك لإنهاء التسجيل',
            full_name: 'الاسم الكامل',
            email: 'البريد الإلكتروني',
            phone: 'رقم الهاتف',
            country: 'البلد',
            continue: 'المتابعة للدفع',
            back_to_info: 'العودة للمعلومات',
            order_summary: 'ملخص الطلب',
            selected_plan: 'الخطة المختارة',
            account_capital: 'رأس مال الحساب',
            total_to_pay: 'إجمالي الدفع',
            payment_method: 'طريقة الدفع',
            securing: 'تأمين المعاملة...',
            secure_msg: 'الدفع مؤمن بتشفير SSL 256 بت. يتم تحرير الأموال فور التأكيد.'
        }
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>('fr');

    const t = (key: string): string => {
        const keys = key.split('.');
        let current = translations[language];
        for (const k of keys) {
            if (current && typeof current === 'object' && k in current) {
                current = current[k];
            } else {
                return key;
            }
        }
        return typeof current === 'string' ? current : key;
    };

    // Adjust document direction for Arabic
    React.useEffect(() => {
        document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
        document.documentElement.lang = language;
    }, [language]);

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
